FROM ubuntu:24.04

RUN apt update && apt upgrade -y
RUN apt install python3 -y

RUN apt-get install apache2 apache2-utils ssl-cert -y
RUN apt-get install libapache2-mod-wsgi-py3 -y
RUN service apache2 restart

COPY para-wsgi.txt .
RUN cat para-wsgi.txt >> /etc/apache2/apache2.conf
RUN rm -rf para-wsgi.txt
