# Generated by Django 5.0.7 on 2024-08-06 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_userModel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('color', models.CharField(max_length=10)),
                ('icon', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Trivia',
            fields=[
                ('triviaID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('questionType', models.CharField(choices=[('text', 'Texto'), ('image', 'Imagen'), ('audio', 'Audio')], max_length=10)),
                ('questionText', models.CharField(blank=True, max_length=200, null=True)),
                ('questionImage', models.CharField(blank=True, max_length=50, null=True)),
                ('questionAudio', models.CharField(blank=True, max_length=50, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('answerID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('answerType', models.CharField(choices=[('text', 'Texto'), ('image', 'Imagen')], max_length=10)),
                ('answerText', models.CharField(blank=True, max_length=200, null=True)),
                ('answerImage', models.CharField(blank=True, max_length=50, null=True)),
                ('correctAnswer', models.BooleanField(default=False)),
                ('trivia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.trivia')),
            ],
        ),
    ]
