# Generated by Django 5.1 on 2024-08-10 03:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_category_trivia_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prize',
            fields=[
                ('prizeCode', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('prizeName', models.CharField(max_length=30)),
                ('prizeType', models.CharField(choices=[('instant', 'Instantáneo'), ('ranking', 'Ranking')], max_length=15)),
                ('appearFrecuency', models.FloatField(default=0, null=True)),
                ('quantity', models.PositiveIntegerField(default=0, null=True)),
                ('rankingPosition', models.PositiveIntegerField(choices=[(1, 'Primer lugar'), (2, 'Segundo lugar'), (3, 'Tercer lugar')], null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('score', models.PositiveIntegerField(default=0)),
                ('position', models.PositiveIntegerField(null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ranking',
                'verbose_name_plural': 'Rankings',
                'ordering': ['-score'],
            },
        ),
        migrations.CreateModel(
            name='PrizeWon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prizeState', models.CharField(choices=[('toBeDelivered', 'Por entregar'), ('sent', 'Enviado'), ('delivered', 'Entregado')], default='toBeDelivered', max_length=15)),
                ('won_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('prize', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.prize')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
