# Generated by Django 5.1 on 2024-08-12 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_prize_ranking_prizewon'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='barVector',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='questionVector',
            field=models.CharField(max_length=70, null=True),
        ),
    ]
